'use strict';
(async()=>{
 const [g,scenes]=await Promise.all(['graph.json','story.json'].map(p=>fetch(p).then(r=>{if(!r.ok)throw Error(p);return r.json()})));
 const colours={checked:'#628aff',reference:'#51d9d0',open:'#ffc565',correction:'#ff818e'};
 const names={checked:'Internally checked within stated assumptions',reference:'Selected published reference — see source record',open:'Open / unproved obligation',correction:'Documented correction to an earlier route'};
 const cat=n=>n.id==='PowerBarrier'?'correction':['CZKnown','NishiokaKnown'].includes(n.id)?'reference':n.state==='checked'?'checked':'open';
 const nodes=new Map(g.nodes.map(n=>[n.id,n])), adj=new Map(g.nodes.map(n=>[n.id,new Set()]));
 g.edges.forEach(e=>{adj.get(e.from).add(e.to);adj.get(e.to).add(e.from)});
 const cvs=document.querySelector('#map'),ctx=cvs.getContext('2d'),$=s=>document.querySelector(s);
 let yaw=.6,pitch=.18,zoom=1,points=[],chosen=null,focus=new Set(),running=false,frame=0,last=0,drag=null,moved=false;
 const enabled=new Set(Object.keys(colours));
 function size(){let d=devicePixelRatio||1;cvs.width=Math.round(cvs.clientWidth*d);cvs.height=Math.round(cvs.clientHeight*d);ctx.setTransform(d,0,0,d,0,0);draw()}
 function project(p){let [x,y,z]=p;let a=x*Math.cos(yaw)+z*Math.sin(yaw),b=-x*Math.sin(yaw)+z*Math.cos(yaw);let yy=y*Math.cos(pitch)-b*Math.sin(pitch),zz=y*Math.sin(pitch)+b*Math.cos(pitch);let scale=Math.min(cvs.clientWidth*.39,cvs.clientHeight*.39)*zoom*3.8/(3.8-zz);return {x:cvs.clientWidth/2+a*scale,y:cvs.clientHeight/2-yy*scale,z:zz};}
 function visible(n){return enabled.has(cat(n))}
 function draw(){let w=cvs.clientWidth,h=cvs.clientHeight;ctx.clearRect(0,0,w,h);let p=new Map(g.nodes.map(n=>[n.id,{...project(n.position),n}]));points=[...p.values()].sort((a,b)=>a.z-b.z);
  let glow=ctx.createRadialGradient(w*.5,h*.5,0,w*.5,h*.5,Math.min(w,h)*.46);glow.addColorStop(0,'#14244488');glow.addColorStop(1,'#14244400');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);
  g.edges.forEach(e=>{let a=p.get(e.from),b=p.get(e.to);if(!visible(a.n)||!visible(b.n))return;let active=focus.has(e.from)||focus.has(e.to);ctx.strokeStyle=active?colours[cat(b.n)]:'#6b90c8';ctx.globalAlpha=focus.size?(active?.65:.035):.13;ctx.lineWidth=active?1.5:.65;ctx.setLineDash(e.dashed?[3,4]:[]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()});ctx.setLineDash([]);
  points.forEach(p=>{if(!visible(p.n))return;let c=cat(p.n),f=focus.has(p.n.id),near=chosen&&adj.get(chosen).has(p.n.id),r=(c==='open'?4.3:3.2)+(p.z+1)*1.2;if(f)r+=4;ctx.globalAlpha=focus.size?(f||near?1:.25):.6+(p.z+1)*.2;ctx.fillStyle=colours[c];ctx.strokeStyle=colours[c];ctx.lineWidth=1.7;ctx.beginPath();if(c==='open'){ctx.moveTo(p.x,p.y-r);ctx.lineTo(p.x+r,p.y);ctx.lineTo(p.x,p.y+r);ctx.lineTo(p.x-r,p.y);ctx.closePath();ctx.stroke()}else{ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill()};if(f){ctx.globalAlpha=.5;ctx.beginPath();ctx.arc(p.x,p.y,r+5,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;ctx.font='12px system-ui';let text=p.n.id.length>23?p.n.id.slice(0,21)+'…':p.n.id;let tw=ctx.measureText(text).width;let tx=Math.min(w-tw-8,Math.max(8,p.x+r+9)),ty=Math.min(h-15,Math.max(20,p.y));ctx.fillStyle='#080e1cee';ctx.fillRect(tx-4,ty-14,tw+8,20);ctx.fillStyle=colours[c];ctx.fillText(text,tx,ty)}});ctx.globalAlpha=1;
 }
 function select(id){let n=nodes.get(id);if(!n)return;chosen=id;focus=new Set([id]);$('#node-id').textContent=n.id;$('#node-label').textContent=n.label;$('#node-state').textContent=names[cat(n)];$('#node-state').style.color=colours[cat(n)];$('#neighbours').textContent=adj.get(id).size+' adjacent nodes · relationships do not by themselves establish an implication.';enabled.add(cat(n));document.querySelector(`[data-group="${cat(n)}"]`).checked=true;draw()}
 function loop(t){if(!running)return;let dt=last?Math.min((t-last)/1000,.05):0;last=t;yaw+=dt*.18;draw();frame=requestAnimationFrame(loop)}
 function stop(){running=false;cancelAnimationFrame(frame);last=0;$('#rotate').textContent='Rotate';$('#rotate').setAttribute('aria-pressed','false')}
 $('#rotate').onclick=()=>{if(running)stop();else{running=true;$('#rotate').textContent='Pause rotation';$('#rotate').setAttribute('aria-pressed','true');frame=requestAnimationFrame(loop)}};
 $('#reset').onclick=()=>{stop();yaw=.6;pitch=.18;zoom=1;chosen=null;focus.clear();draw()};$('#clear').onclick=()=>{chosen=null;focus.clear();draw()};$('#zoom-in').onclick=()=>{zoom=Math.min(1.7,zoom+.15);draw()};$('#zoom-out').onclick=()=>{zoom=Math.max(.5,zoom-.15);draw()};
 cvs.onpointerdown=e=>{stop();drag=[e.clientX,e.clientY];moved=false;cvs.setPointerCapture(e.pointerId)};cvs.onpointermove=e=>{if(!drag)return;let dx=e.clientX-drag[0],dy=e.clientY-drag[1];if(Math.abs(dx)+Math.abs(dy)>2)moved=true;yaw+=dx*.008;pitch=Math.max(-1.3,Math.min(1.3,pitch+dy*.008));drag=[e.clientX,e.clientY];draw()};cvs.onpointerup=e=>{drag=null;if(moved)return;let r=cvs.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;let n=points.filter(p=>visible(p.n)&&Math.hypot(p.x-x,p.y-y)<13).sort((a,b)=>b.z-a.z)[0];if(n)select(n.n.id)};cvs.onpointercancel=()=>drag=null;
 cvs.onkeydown=e=>{let used=true;switch(e.key){case'ArrowLeft':yaw-=.12;break;case'ArrowRight':yaw+=.12;break;case'ArrowUp':pitch-=.12;break;case'ArrowDown':pitch+=.12;break;case'+':case'=':zoom=Math.min(1.7,zoom+.1);break;case'-':zoom=Math.max(.5,zoom-.1);break;default:used=false}if(used){e.preventDefault();stop();draw()}};
 document.querySelectorAll('[data-group]').forEach(el=>el.onchange=()=>{el.checked?enabled.add(el.dataset.group):enabled.delete(el.dataset.group);draw()});
 $('#search').oninput=e=>{let q=e.target.value.trim().toLowerCase();$('#results').replaceChildren();if(!q)return;g.nodes.filter(n=>(n.id+' '+n.label).toLowerCase().includes(q)).slice(0,12).forEach(n=>{let b=document.createElement('button');b.textContent=n.id+' · '+n.label;b.onclick=()=>select(n.id);$('#results').append(b)})};
 document.querySelectorAll('[data-scene]').forEach(b=>b.onclick=()=>{let s=scenes.find(x=>x.id===b.dataset.scene);stop();select(s.focus[0]);focus=new Set(s.focus);$('#node-id').textContent=s.kicker;$('#node-label').textContent=s.lines.join('. ');$('#node-state').textContent=s.title;$('#neighbours').textContent='Highlighted IDs: '+s.focus.join(', ');draw()});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});new ResizeObserver(size).observe(cvs);size();
})().catch(e=>{document.querySelector('#node-label').textContent='The graph could not load. Please reload or use the original map link below.';console.error(e)});
